### ISSUE TITLE
Move to slim-template organization

### ISSUE THREAD

**Issue by minad** [slim-template/Slim-Sugar#1]
Hi ,

do you want to transfer this repo to the slim-template organization? I will give you access there if you want.

Daniel (@minad, for the Slim team)

**Comment by CiiDub** [comment]
Ya, you bet.  It's kind of a mess. I switched away from Espresso, and they never really added support for significant whitespace anyway. So it's hack(y), try to make navigation work like other languages.

Keep up the good work.  Slim is very very nice.  I use it on all my projects.

**Comment by minad** [comment]
So shall we transfer?

**Comment by minad** [comment]
I made you admin at slim-template, so you can transfer and you will have all rights there. This step is just to collect all slim related repositories. We want you as maintainer, but you can also give up maintainership if you don't use it anymore. In this case we would flag the repository as unmaintained.

**Comment by CiiDub** [comment]
Ok it's done.  And I will give up maintainer status.

**Comment by minad** [comment]
That's unfortunate :(
